import React, { createContext, useContext, useEffect, useState } from "react";
import type { PlatformSettings, PublicCategory, PublicProduct, PublicSeller } from "../types";

interface DataState {
  products: PublicProduct[];
  sellers: PublicSeller[];
  categories: PublicCategory[];
  settings: PlatformSettings | null;
  loading: boolean;
  error: string | null;
}

const DataContext = createContext<DataState>({
  products: [],
  sellers: [],
  categories: [],
  settings: null,
  loading: true,
  error: null,
});

// All four files are generated by the backend's publish pipeline and
// committed to this repo under /public-data — the site NEVER calls the
// private backend API to render pages, so it keeps working even if the
// backend/admin server is offline (spec section 37).
async function loadJson<T>(path: string): Promise<T> {
  const base = import.meta.env.BASE_URL || "/";
  const url = `${base.replace(/\/$/, "")}/public-data/${path}?v=${Date.now()}`;
  const res = await fetch(url, { cache: "no-store" });
  if (!res.ok) throw new Error(`ناموفق در بارگذاری ${path} (${res.status})`);
  return res.json();
}

export function DataProvider({ children }: { children: React.ReactNode }) {
  const [state, setState] = useState<DataState>({
    products: [],
    sellers: [],
    categories: [],
    settings: null,
    loading: true,
    error: null,
  });

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const [products, sellers, categories, settings] = await Promise.all([
          loadJson<PublicProduct[]>("products.json"),
          loadJson<PublicSeller[]>("sellers.json"),
          loadJson<PublicCategory[]>("categories.json"),
          loadJson<PlatformSettings>("settings.json"),
        ]);
        if (!cancelled) setState({ products, sellers, categories, settings, loading: false, error: null });
      } catch (err) {
        if (!cancelled) {
          setState((s) => ({
            ...s,
            loading: false,
            error: err instanceof Error ? err.message : "خطای نامشخص در بارگذاری داده‌ها",
          }));
        }
      }
    })();
    return () => {
      cancelled = true;
    };
  }, []);

  return <DataContext.Provider value={state}>{children}</DataContext.Provider>;
}

export function useData() {
  return useContext(DataContext);
}
