import React, {
  createContext,
  useContext,
  useEffect,
  useState,
} from "react";

import type {
  PlatformSettings,
  PublicCategory,
  PublicProduct,
  PublicSeller,
} from "../types";

interface DataState {
  products: PublicProduct[];
  sellers: PublicSeller[];
  categories: PublicCategory[];
  settings: PlatformSettings | null;
  loading: boolean;
  error: string | null;
}

const initialState: DataState = {
  products: [],
  sellers: [],
  categories: [],
  settings: null,
  loading: true,
  error: null,
};

const DataContext =
  createContext<DataState>(initialState);

/*
 * Public data is generated by the backend publish
 * pipeline and committed to /public-data.
 *
 * The public storefront intentionally does not
 * depend on the private backend API for rendering.
 */

async function loadJson<T>(
  path: string,
  signal?: AbortSignal
): Promise<T> {
  const base =
    import.meta.env.BASE_URL || "/";

  const normalizedBase =
    base.replace(/\/+$/, "");

  const url =
    `${normalizedBase}/public-data/${path}?v=${Date.now()}`;

  const response = await fetch(url, {
    cache: "no-store",
    signal,
    headers: {
      Accept: "application/json",
    },
  });

  if (!response.ok) {
    throw new Error(
      `ناموفق در بارگذاری ${path} (${response.status})`
    );
  }

  try {
    return (await response.json()) as T;
  } catch {
    throw new Error(
      `فایل ${path} دارای JSON معتبر نیست`
    );
  }
}


async function hydrateMissingSellerLogos(
  sellers: PublicSeller[],
  signal: AbortSignal
): Promise<PublicSeller[]> {
  const apiUrl = ((import.meta.env.VITE_API_URL as string | undefined) || "https://threedmarketiran-backend.onrender.com").replace(/\/+$/, "");

  const results = await Promise.allSettled(
    sellers.map(async (seller) => {
      // Published snapshots are the source of truth. Only ask the API for a
      // logo when the snapshot genuinely has no logo URL; this keeps the
      // public site fast and portable when moved off GitHub Pages.
      if (seller.logoUrl) return null;
      const response = await fetch(
        `${apiUrl}/api/sellers/by-slug/${encodeURIComponent(seller.slug)}`,
        { signal, headers: { Accept: "application/json" } }
      );
      if (!response.ok) return null;
      const data = (await response.json()) as { seller?: { logoUrl?: string | null } };
      if (!data.seller?.logoUrl && !seller.logoUrl) return null;
      return {
        slug: seller.slug,
        logoUrl: `${apiUrl}/api/sellers/by-slug/${encodeURIComponent(seller.slug)}/logo`,
      };
    })
  );

  const logoBySlug = new Map<string, string>();
  for (const result of results) {
    if (result.status === "fulfilled" && result.value) {
      logoBySlug.set(result.value.slug, result.value.logoUrl);
    }
  }

  return sellers.map((seller) => ({
    ...seller,
    logoUrl: logoBySlug.get(seller.slug) ?? seller.logoUrl,
  }));
}

function validateArray<T>(
  value: unknown,
  name: string
): T[] {
  if (!Array.isArray(value)) {
    throw new Error(
      `ساختار ${name} معتبر نیست`
    );
  }

  return value as T[];
}

export function DataProvider({
  children,
}: {
  children: React.ReactNode;
}) {
  const [state, setState] =
    useState<DataState>(initialState);

  useEffect(() => {
    const controller =
      new AbortController();

    let mounted = true;

    async function loadData() {
      try {
        if (mounted) {
          setState((current) => ({
            ...current,
            loading: true,
            error: null,
          }));
        }

        const [
          productsData,
          sellersData,
          categoriesData,
          settingsData,
        ] = await Promise.all([
          loadJson<unknown>(
            "products.json",
            controller.signal
          ),
          loadJson<unknown>(
            "sellers.json",
            controller.signal
          ),
          loadJson<unknown>(
            "categories.json",
            controller.signal
          ),
          loadJson<PlatformSettings>(
            "settings.json",
            controller.signal
          ),
        ]);

        if (!mounted) return;

        const products =
          validateArray<PublicProduct>(
            productsData,
            "products.json"
          );

        const sellers =
          await hydrateMissingSellerLogos(
            validateArray<PublicSeller>(
              sellersData,
              "sellers.json"
            ),
            controller.signal
          );

        const categories =
          validateArray<PublicCategory>(
            categoriesData,
            "categories.json"
          );

        setState({
          products,
          sellers,
          categories,
          settings: settingsData,
          loading: false,
          error: null,
        });
      } catch (error) {
        if (!mounted) return;

        /*
         * AbortError normally means the component was
         * unmounted. We do not expose it as a page error.
         */
        if (
          error instanceof DOMException &&
          error.name === "AbortError"
        ) {
          return;
        }

        const message =
          error instanceof Error
            ? error.message
            : "خطای نامشخص در بارگذاری داده‌ها";

        setState((current) => ({
          ...current,
          loading: false,
          error: message,
        }));
      }
    }

    loadData();

    return () => {
      mounted = false;
      controller.abort();
    };
  }, []);

  return (
    <DataContext.Provider value={state}>
      {children}
    </DataContext.Provider>
  );
}

export function useData() {
  return useContext(DataContext);
}
