// Mirrors the public data contract written by
// backend/src/services/publishService.ts.
//
// Keep this file synchronized with the public-data
// JSON generated by the backend publish pipeline.

export interface PublicImage {
  url: string;
  isPrimary: boolean;
}

export interface PublicModel {
  kind: "GLB" | "GLTF" | "USDZ";
  url: string;
}

export interface PublicDimensions {
  widthM: number | null;
  heightM: number | null;
  depthM: number | null;
  realWorldScale: true;
}

export interface PublicProduct {
  id: string;
  slug: string;
  name: string;
  shortDescription: string | null;
  fullDescription: string | null;
  tags: string[];
  material?: string | null;
  colors?: Array<{ name: string; value: string }>;
  price: number | null;
  isPinned?: boolean;
  pinOrder?: number | null;
  viewCount?: number;
  seller: {
    id: string;
    slug: string;
    storeName: string;
  };
  images: PublicImage[];
  models: PublicModel[];
  dimensions: PublicDimensions | null;
  publishedAt: string | null;
}

export interface PublicSeller {
  id: string;
  slug: string;
  storeName: string;
  description: string | null;
  logoUrl: string | null;
  themeColor?: string | null;
  contactEmail: string | null;
  contactPhone: string | null;
  address: string | null;
  socialLinks: Record<string, string> | null;
}

export interface PublicPlan {
  id: string;
  name: string;
  durationDays: number;
  price: number;
  discountPct?: number | null;
  productLimit?: number | null;
  storageLimitMb?: number | null;
  trafficLimitGb?: number | null;
  categoryId?: string | null;
  sortOrder?: number;
  features?: Record<string, unknown> | null;
}

export interface PublicPlanCategory {
  id: string;
  name: string;
  slug: string;
  description?: string | null;
  sortOrder?: number;
  isActive?: boolean;
}

export interface PlatformSettings {
  platformName: string;
  logoUrl?: string | null;
  faviconUrl?: string | null;
  colorPrimary: string;
  colorSecondary: string;
  colorAccent: string;
  colorBackground: string;
  colorText: string;
  fontFamily: string;
  socialLinks?: Record<string, string> | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
}


export interface PublicCatalog {
  schemaVersion: number;
  generatedAt: string;
  version: string;
  products: PublicProduct[];
  sellers: PublicSeller[];
  settings: PlatformSettings;
  plans: PublicPlan[];
  planCategories?: PublicPlanCategory[];
}
